encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/random", views.random, name="random"),
    path("wiki/add.html", views.add, name="add"),
    path("wiki/<str:name>", views.entry, name="name"),
    path("search", views.search, name="search"),
    path("edit/<str:name>", views.edit, name="edit")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.http import HttpResponse, HttpResponseRedirect
from http.client import HTTPResponse
from django import forms
from django.shortcuts import render, redirect
from django.urls import reverse
from markdown2 import Markdown
from random import randint

from . import util

class NewEntryForm(forms.Form):
    title = forms.CharField(label="New Entry")
    textarea = forms.CharField(widget=forms.Textarea)

class EditEntryForm(forms.Form):
    textarea = forms.CharField(widget=forms.Textarea)

markdowner = Markdown()

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def entry(request, name):
    if util.get_entry(name) is None:
        return render(request, "encyclopedia/error.html", {
            "error": "Entry does not exist"
        })
    else:
        parsed_content = markdowner.convert(util.get_entry(name))
        return render(request, "encyclopedia/entry.html", {
            "name": name,
            "entry": parsed_content
        })

def search(request):
    q = request.GET["q"]

    if util.get_entry(q):
        parsed_content = markdowner.convert(util.get_entry(q))
        return render(request, "encyclopedia/entry.html", {
            "name": util.get_entry(q),
            "entry": parsed_content
        })

    matchedEntries = []
    for entry in util.list_entries():
        if q in entry:
            matchedEntries.append(entry)

    if matchedEntries:
        return render(request, "encyclopedia/search.html", {
            "entries": matchedEntries
        })

    else:
        return render(request, "encyclopedia/error.html", {
            "error": "This entry does not exist"
        })

def add(request):
    if request.method == "POST":
        form = NewEntryForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            textarea = form.cleaned_data["textarea"]
            if title in util.list_entries():
                return render(request, "encyclopedia/error.html", {
                "error": "This entry already exists"
                })
            else:
                # f = open(f"./entries/{title}.md", "a")
                # f.write(textarea)
                util.save_entry(title, textarea)
                parsed_content = markdowner.convert(textarea)
                return render(request, "encyclopedia/entry.html", {
                "name": title,
                "entry": parsed_content
                })
        else:
            return render(request, "encyclopedia/add.html", {
                "form": form
            })

    return render(request, "encyclopedia/add.html", {
        "form": NewEntryForm()
    })

def edit(request, name):
    if request.method == "GET":
        my_entry = util.get_entry(name)
        return render(request, "encyclopedia/edit.html", {
            'form': EditEntryForm(initial={'textarea': my_entry}),
            'name': name
        })

    else:
        form = EditEntryForm(request.POST)
        if form.is_valid():
            textarea = form.cleaned_data["textarea"]
            util.save_entry(name, textarea)
            my_entry = util.get_entry(name)
            parsed_content = markdowner.convert(textarea)
            return render(request, "encyclopedia/entry.html", {
            "name": name,
            "entry": parsed_content
            })
        else:
            return render(request, "encyclopedia/edit.html")

def random(request):
    entries = util.list_entries()
    n = randint(0, len(entries) -1)
    name = entries[n]
    parsed_content = markdowner.convert(util.get_entry(name))
    return render(request, "encyclopedia/entry.html", {
    "name": name,
    "entry": parsed_content
    })

encyclopedia/templates/encyclopedia/add.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}

    <h1>Add entry</h1>
    <form action="{% url 'encyclopedia:add' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit">
    </form>
    <p>Click the "Submit" button and a new entry for the encyclopedia will be created</p>
    
{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}

    <h1>Edit {{ name }}</h1>
    <form action="{% url 'encyclopedia:edit' name=name %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit">
    </form>
    <p>Click the "Submit" button to edit the Markdown content of the entry</p>

{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    {{ entry | safe }}

    <a href="{% url 'encyclopedia:edit' name=name %}">Edit Markdown Content</a>
    
{% endblock %}

encyclopedia/templates/encyclopedia/error.html
<!DOCTYPE html>
<html lang="en">


    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Bootstrap 5 404 Error Page</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    </head>


    <body>
        <div class="d-flex align-items-center justify-content-center vh-100">
            <div class="text-center">
                <h1 class="display-1 fw-bold">404</h1>
                <p class="fs-3"> <span class="text-danger">Opps!</span> Page not found.</p>
                <p class="lead">
                    {{ error }}
                </p>
                  <a href="{% url 'encyclopedia:index' %}" class="btn btn-primary">Home</a>
            </div>
        </div>
    </body>


</html>

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href ="/wiki/{{entry}}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="get">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:add' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/random.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    {{ entry | safe }}

    <a href="{% url 'encyclopedia:edit' name=name %}">Edit Markdown Content</a>
    
{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <ul>
        {% if entries is None %}
            <h1>Search did not match any results</h1>
        {% else %}
            {% for entry in entries %}
                <li><a href ="/wiki/{{entry}}">{{ entry }}</a></li>
            {% endfor %}
        {% endif %}
    </ul>
{% endblock %}